### ISSUE TITLE
Bug in link on home page

### ISSUE THREAD

**Issue by 42ABC** [statsmaths/statsmaths.github.io#1]
The "DSST 289: Data Science (Fall 2020) [html]" link under "Recent Course Websites" on the home page is broken. Currently it is linking to https://statsmaths.github.io/stat289-f20/ (which doesn't exist), but I think it should link to https://statsmaths.github.io/dsst289-f21/ instead (and the year be renamed to Data Science (Fall 2021)).

**Comment by NaincyKumariKnoldus** [comment]
Hello @42ABC can i solve this please?

**Comment by NaincyKumariKnoldus** [comment]
Hey @42ABC I have raised a PR for this now. Please review and merge it.
Thanks!
